### ISSUE TITLE
Demo does not compile

### ISSUE THREAD

**Issue by galatyn** [DanielGausi/AudioWerkzeugeBibliothek#1]
Tried to compile DemoSimple:
- project has a link to missing icon file
- some of units (M4aAtoms.pas for example) has a typo, doubble curly bracket:
```
     AudioFileBasics {$IFDEF USE_SYSTEM_TYPES}}, System.Types{$ENDIF};
```
Small issues, but it may create bad first impression.

**Comment by DanielGausi** [comment]
Hi, sorry for not responding - I wasn't noticed about that issue. 

However, during my work on an update for my mp3-Player Nemp I fixed these issues (and some more, including a little memory leak), and made some minor improvements I needed for the player.

**Comment by DanielGausi** [comment]
obsolete with version 3, I would think.
